/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main.devGui;

import gl.lighting.Shadow;

/**
 *
 * @author Rene
 */
public class LightDirGui extends javax.swing.JFrame
{

    
    public LightDirGui()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pitchSlide = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yawSlide = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        rollSlide = new javax.swing.JSlider();
        offsetSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pitchSlide.setMaximum(365);
        pitchSlide.setMinimum(-365);
        pitchSlide.setValue(-69);
        pitchSlide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                pitchSlideMouseDragged(evt);
            }
        });

        jLabel1.setText("Pitch");

        jLabel2.setText("Yaw");

        yawSlide.setMaximum(365);
        yawSlide.setMinimum(-365);
        yawSlide.setValue(224);
        yawSlide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                yawSlideMouseDragged(evt);
            }
        });

        jLabel3.setText("Roll");

        rollSlide.setMaximum(365);
        rollSlide.setMinimum(-365);
        rollSlide.setValue(0);
        rollSlide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                rollSlideMouseDragged(evt);
            }
        });

        offsetSlider.setMaximum(1000);
        offsetSlider.setMinimum(-1000);
        offsetSlider.setValue(10);
        offsetSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                offsetSliderMouseDragged(evt);
            }
        });

        jLabel4.setText("Offset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rollSlide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pitchSlide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yawSlide, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(offsetSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pitchSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yawSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rollSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(offsetSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pitchSlideMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_pitchSlideMouseDragged
    {//GEN-HEADEREND:event_pitchSlideMouseDragged
        Shadow.pitchC = pitchSlide.getValue();
        Shadow.remap();
    }//GEN-LAST:event_pitchSlideMouseDragged

    private void yawSlideMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_yawSlideMouseDragged
    {//GEN-HEADEREND:event_yawSlideMouseDragged
        Shadow.yawC = yawSlide.getValue();
        Shadow.remap();
    }//GEN-LAST:event_yawSlideMouseDragged

    private void rollSlideMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rollSlideMouseDragged
    {//GEN-HEADEREND:event_rollSlideMouseDragged
        Shadow.rollC = rollSlide.getValue();
        Shadow.remap();
    }//GEN-LAST:event_rollSlideMouseDragged

    private void offsetSliderMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_offsetSliderMouseDragged
    {//GEN-HEADEREND:event_offsetSliderMouseDragged
        Shadow.moveMultiplier = offsetSlider.getValue();
        Shadow.remap();
    }//GEN-LAST:event_offsetSliderMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSlider offsetSlider;
    private javax.swing.JSlider pitchSlide;
    private javax.swing.JSlider rollSlide;
    private javax.swing.JSlider yawSlide;
    // End of variables declaration//GEN-END:variables
}
